mod.id = "svocore"
mod.name = "SVO Core"
mod.group = "me.pajic"
mod.version = "26.1.4"

deps.fabric_loader = "0.19.2"
deps.mixson = "2.2.0"
deps.mixinconstraints = "1.1.0"
loomx.loom_version = "1.16-SNAPSHOT"

mod.modrinth_id = "WVBuQZId"

["26.1"]
mod.mc_compat = "~26.1"
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]
deps.fabric_api = "0.150.0+26.1.2"
deps.modmenu = "18.0.0-beta.1"
deps.fzzy_config = "0.7.6+26.1-pre-3"
deps.sodium = "0.8.10+mc26.1.2"